name: Deployment Dev
run-name: ${{ github.actor }} running a deployment 🚀
on:
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: NodeJs Build
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm ci
      - run: npm run build
      - run: cp -r dist html
      - name: deploy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "html"
          target: "~/bybraunsinfrastructure/static-web-server-dev/"
      - run: echo "This job's status is ${{ job.status }}."
